---
addons:
  apt:
    packages:
      - aspell
      - aspell-en
before_install:
  - 'cpanm --notest App::cpm'
  - 'eval $(curl https://travis-perl.github.io/init) --auto'
  - 'AUTHOR_TESTING=0 cpm install --workers $(test-jobs) --global Code::TidyAll::Plugin::SortLines::Naturally Code::TidyAll::Plugin::UniqueLines Perl::Tidy'
cache:
  directories:
    - '~/perl5'
install:
  - 'cpan-install --coverage   # installs coverage prereqs, if enabled'
  - 'AUTHOR_TESTING=0 cpm install --cpanfile cpanfile --workers $(test-jobs) --global --with-recommends --with-suggests --with-configure --with-develop'
language: perl
matrix: {}
notifications:
  email:
    on_failure: alway
    on_success: always
    recipients:
      - olaf@wundersolutions.com
perl:
  - '5.10'
  - '5.12'
  - '5.14'
  - '5.16'
  - '5.18'
  - '5.20'
  - '5.22'
  - '5.24'
  - '5.26'
script:
  - 'prove -lrv t'
sudo: 'false'
